spring:
  application:
    name: "common"
  jpa:
    hibernate:
      ddl-auto: "update"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
    driver-class-name: "org.postgresql.Driver"