name: Deploy e-wallet Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and install OpenJDK 22
        run: |
          JDK_VERSION=22
          INSTALL_DIR=$HOME/openjdk
          wget https://download.java.net/openjdk/jdk22/ri/openjdk-22_linux-x64_bin.tar.gz -P /tmp
          mkdir -p $INSTALL_DIR
          tar -xzf /tmp/openjdk-22_linux-x64_bin.tar.gz -C $INSTALL_DIR
          echo "JAVA_HOME=$INSTALL_DIR/jdk-22" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Verify Java installation
        run: |
          java -version

      - name: Build with Maven
        run: mvn clean install

      - name: Upload the JAR to EC2
        env:
          EC2_HOST: "some-host-name"
          EC2_USER: "some-user-name"
        run: |
          JAR_FILE: ./user-accounts/target/*.jar
          echo "Found JAR file: $JAR_FILE"
            
          scp -i ~/.ssh/id_rsa $JAR_FILE $EC2_USER$EC2_HOST:/home/$EC2_USER/

      - name: Deploy the JAR on EC2
        env:
          EC2_HOST: "some-host-name"
          EC2_USER: "some-user-name"
        run: |
          ssh -i ~./ssh/id_rsa $EC2_USER$EC2_HOST << 'EOF'
            # Kill any spring boot application running on the default port
            PID=$(lsof -t -i:7070)
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
          
            # Run the new JAR file
            JAR_FILE=$(ls -t /home/$EC2_USER/*jar | head -n 1)
            nohup java -jar $JAVA_FILE > spring-boot-app.log 2>&1 &
          EOF
